version: '3.1'

services:
  joomla:
    image: joomla:3.4.3
    volumes:
      - "./etc:/var/www/html"
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: password

  joomladb:
    image: mysql:5.6
    volumes:
      - "./docker-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password